apiVersion: v1
kind: Service
metadata:
  name: chat-server-service
  labels:
    app: chat-server-service
spec:
  type: LoadBalancer
  ports:
    - port: 50052
      name: grpc
      targetPort: 50052
  selector:
    app: chat-server